### ISSUE TITLE
DB Connections Issue

### ISSUE THREAD

**Issue by sajeev-adroitminds** [adamfoneil/Dapper.Repository#22]
Hi Adam,

I see how you create the connection on each request. This I believe is a bad practice when you think of using this in say a web-based application. A single request could have multiple DB calls and this framework will have single DB connection open and closed every time a DB call is requested. There should be unit of work wrapper which handles the DB Connection creation and disposal with each web request having the single db connection being used per request instead of per DB call.

I am open to contribute with the way I did the implementation in the library I created for my organization.

**Comment by adamfoneil** [comment]
Thanks for reaching out. I've considered this also, but I would need to be on board with any breaking changes. If I have to rework or retrofit a lot in the app where I'm using it, that would not be good. I'm curious to see your approach, and I'll pay you if I like it. My email is on my profile I think, so please email me with your billing rate and anything else relevant.
